using System;
using System.IO;

namespace ClinicaLongevidadApp.Services
{
    /// <summary>
    /// Centralized application output paths. All files generated by the app
    /// should use these properties so output is grouped under a single
    /// folder with well-known subfolders.
    /// </summary>
    public static class AppPaths
    {
        // Top-level folder name under LocalApplicationData and CommonApplicationData
        private const string AppFolderName = "ClinicaLongevidadAppArtifacts";

        private static string EnsureDir(string path)
        {
            try { Directory.CreateDirectory(path); } catch { }
            return path;
        }

        public static string BaseDir => EnsureDir(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), AppFolderName));

        public static string BackupsDir => EnsureDir(Path.Combine(BaseDir, "backups"));
        public static string LogsDir => EnsureDir(Path.Combine(BaseDir, "logs"));
        public static string KeysDir => EnsureDir(Path.Combine(BaseDir, "keys"));
        public static string ReportsDir => EnsureDir(Path.Combine(BaseDir, "reports"));
        public static string IntegrityReportsDir => EnsureDir(Path.Combine(ReportsDir, "integrity"));
        public static string DiagnosticsDir => EnsureDir(Path.Combine(ReportsDir, "diagnostics"));
        public static string ExportsDir => EnsureDir(Path.Combine(BaseDir, "exports"));
        public static string AuditArtifactsDir => EnsureDir(Path.Combine(BaseDir, "audit_artifacts"));
        public static string AuditManifestsDir => EnsureDir(Path.Combine(AuditArtifactsDir, "manifests"));

        // Locations under CommonApplicationData for reports intended to be shared
        public static string CommonBaseDir => EnsureDir(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), AppFolderName));
        public static string CommonAuditArtifactsDir => EnsureDir(Path.Combine(CommonBaseDir, "AuditArtifacts"));
        public static string CommonAuditReportsDir => EnsureDir(Path.Combine(CommonBaseDir, "AuditIntegrityReports"));
    }
}
